### ISSUE TITLE
Search for a user published Nanopubs using the grlc Search API

### ISSUE THREAD

**Issue by vemonet** [peta-pico/nanopub-api#1]
I am trying to retrieve all nanopublications from a given user

Let say the user with the following ORCID: https://orcid.org/0000-0002-1501-1082 (I know him, he posted a few nanopubs)

**Is it possible to ask for all nanopublications published by a specific ORCID from the grlc API?**

Taking a first look at the grlc API, it does not seems to present this feature: http://grlc.nanopubs.lod.labs.vu.nl/api/local/local

But it is possible to do it using the Nanobench:

http://localhost:37373/user?1&id=https://orcid.org/0000-0002-1501-1082

Additionally I would like to: filter on a specific URI or `rdf:type` (or even string, but URI will be much faster to filter on)

> This seems to be already implemented, but not with the ability to filter on the user who published the nanopubs

**Why do I want to do that?**

Be able to easily retrieve all (or some of) my nanopubs automatically in a simple API call (to update a profile for example and use nanopubs to share links with comments like I would do with twitter or else)

**Comment by tkuhn** [comment]
This is possible for signed nanopublications with find_signed_* calls. Users are identified by public key, but you can get the mapping by calling get_all_users. This is not scalable once we have a lot of users, but maybe we can worry about that later.

**Comment by vemonet** [comment]
Thanks! I gave it a try:

### Getting the user pubkey

I tried the get_all_users call but faced an issue with the call generated by the Swagger UI:
```bash
curl -X GET "http://grlc.nanopubs.lod.labs.vu.nl/api/local//get_all_users" -H  "accept: text/csv"
```

I made it work by removing an extra `/` and adding the second `/local` in the URL call:
```bash
curl -X GET "http://grlc.nanopubs.lod.labs.vu.nl/api/local//get_all_users" -H  "accept: text/csv"
```

The call could be improved by filtering on the user name, using the Search index of Virtuoso it should resolve fast enough

### Getting all publications from a user

My pubkey is: 
```
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCR9fz0fKCdWOWC+pxhkQhEM/ppbdIYe5TLSdj+lJzSlv9mYBaPgrzVezSwwbmhlHBPDZa4/vHycU315BdmUGq+pXllp9+rWFfrb+kBJwhZjpG6BeyyXBsRFz4jmQVxl/ZYHilQTh/XalYzKkEAyTiEMPee4Kz61PaWOKH24CsnOQIDAQAB
```

Trying to get all nanopubs from this pubkey using `find_signed_nanopubs`:
Same issue related to the Swagger UI generating a wrong URL:
```bash
curl -X GET "http://grlc.nanopubs.lod.labs.vu.nl/api/local//find_signed_nanopubs?pubkey=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCR9fz0fKCdWOWC%2BpxhkQhEM%2FppbdIYe5TLSdj%2BlJzSlv9mYBaPgrzVezSwwbmhlHBPDZa4%2FvHycU315BdmUGq%2BpXllp9%2BrWFfrb%2BkBJwhZjpG6BeyyXBsRFz4jmQVxl%2FZYHilQTh%2FXalYzKkEAyTiEMPee4Kz61PaWOKH24CsnOQIDAQAB" -H  "accept: text/csv"
```

Fixed the same way as for `get_all_users` (remove extra `/` and add a `/local`)
```bash
curl -X GET "http://grlc.nanopubs.lod.labs.vu.nl/api/local/local/find_signed_nanopubs?pubkey=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCR9fz0fKCdWOWC%2BpxhkQhEM%2FppbdIYe5TLSdj%2BlJzSlv9mYBaPgrzVezSwwbmhlHBPDZa4%2FvHycU315BdmUGq%2BpXllp9%2BrWFfrb%2BkBJwhZjpG6BeyyXBsRFz4jmQVxl%2FZYHilQTh%2FXalYzKkEAyTiEMPee4Kz61PaWOKH24CsnOQIDAQAB" -H  "accept: text/csv"
```

> Successfully returns the URIs of all published nanopubs!

### Retrieving the content of the nanopublications:

The grlc API returns a csv looking like:
```
"http://purl.org/np/RAVF_WDsJRkRXXWgaJx5p9EnjLIguIv0-GqDlbfBtBPcQ",2020-04-14T12:13:44.817Z,"MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCR9fz0fKCdWOWC+pxhkQhEM/ppbdIYe5TLSdj+lJzSlv9mYBaPgrzVezSwwbmhlHBPDZa4/vHycU315BdmUGq+pXllp9+rWFfrb+kBJwhZjpG6BeyyXBsRFz4jmQVxl/ZYHilQTh/XalYzKkEAyTiEMPee4Kz61PaWOKH24CsnOQIDAQAB",0,0
"http://purl.org/np/RAc99KPv1qM3J6tyIpYRY3yh1LR5u15FwByJ78-k4Ix6E",2020-07-08T13:11:40.328Z,"MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCR9fz0fKCdWOWC+pxhkQhEM/ppbdIYe5TLSdj+lJzSlv9mYBaPgrzVezSwwbmhlHBPDZa4/vHycU315BdmUGq+pXllp9+rWFfrb+kBJwhZjpG6BeyyXBsRFz4jmQVxl/ZYHilQTh/XalYzKkEAyTiEMPee4Kz61PaWOKH24CsnOQIDAQAB",0,0
```

Content needs to be retrieved for each nanopublication

Here we use the URI returned by the grlc API:
```bash
curl -X GET "http://purl.org/np/RAc99KPv1qM3J6tyIpYRY3yh1LR5u15FwByJ78-k4Ix6E"  -H "accept: application/n-quads"
```

But the pURL URI does not seems to resolve:
```html
<!DOCTYPE HTML>
<html>
<head>
<title>302 Found</title>
</head>
<body>
<h1>Found</h1>
<p>The resource requested is available <a href="http://server.nanopubs.lod.labs.vu.nl/RAc99KPv1qM3J6tyIpYRY3yh1LR5u15FwByJ78-k4Ix6E">here</a>.<p>
</body>
</html>
```

Trying using the URI returned by the error when the purl.org URI is requested:
```bash
curl -X GET "http://server.nanopubs.lod.labs.vu.nl/RAc99KPv1qM3J6tyIpYRY3yh1LR5u15FwByJ78-k4Ix6E" -H "accept: application/n-quads"
```
The nanopub content is returned, but in the HTML format instead of N-quads (same for turtle)



What would be the best approach to retrieve a nanopublication content as RDF (n-quads preferably to keep graph information)  using curl and the nanopublication URI?

**Comment by tkuhn** [comment]
Yes, it has to be `api/local/local/`. The Swagger UI shows it wrong. I think this is fixed in the latest version of grlc, but other things are not backwards compatible, which prevents a fast upgrade.

Agreed that user name filtering for `get_all_users` would be nice. But I think it's not possible to make that an optional argument. So, either you would always have to set the user name search string (though it couild be just a blank), or I would have to make it a separate call (like `get_all_users_by_name`). Feel free to open an issue in GitHub, and I will try to look into it.

When using curl to resolve the URIs, you need to use the `-L` flag to follow redirects.

The content types are a bit confusing because several of the RDF serializations seem to have several of them. The nanopub server is only recognizing `text/x-nquads` for N-Quads (I don't remember why it uses this one; I think it's the standard used by Sesame/RDF4J). Turtle doesn't work because only graph formats are supported, but `application/trig` works.

I hope this answers all your questions?

**Comment by vemonet** [comment]
Thanks! The following call works perfectly:

```
curl -L -X GET "http://purl.org/np/RAc99KPv1qM3J6tyIpYRY3yh1LR5u15FwByJ78-k4Ix6E"  -H "accept: text/x-nquads"
```
